# Macro for adding sources from subfolders
MACRO(ADD_SOURCES VAR_NAME DIR_NAME)
    FILE(GLOB_RECURSE ${VAR_NAME}
        ${CMAKE_CURRENT_SOURCE_DIR}/${DIR_NAME}/*.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/${DIR_NAME}/*.hpp)
ENDMACRO()

# Macro for enabling c++11 as standard
MACRO(ENABLE_CXX_11 TARGET_NAME)
    SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES CXX_STANDARD 11)
    SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES CXX_STANDARD_REQUIRED ON)
ENDMACRO()
