# Version for Restore
SET(RESTORE_VERSION "0.0.1")

STRING(REGEX MATCHALL "[0-9]" VERSION_PARTS "${RESTORE_VERSION}")
LIST(GET VERSION_PARTS 0 RESTORE_VERSION_MAJOR)
LIST(GET VERSION_PARTS 1 RESTORE_VERSION_MINOR)
LIST(GET VERSION_PARTS 2 RESTORE_VERSION_PATCH)
