# Version for Restore
set(RESTORE_VERSION "0.0.1")

string(REGEX MATCHALL "[0-9]" VERSION_PARTS "${RESTORE_VERSION}")
list(GET VERSION_PARTS 0 RESTORE_VERSION_MAJOR)
list(GET VERSION_PARTS 1 RESTORE_VERSION_MINOR)
list(GET VERSION_PARTS 2 RESTORE_VERSION_PATCH)
